services:
  MicroModule\Saga\Storage\DBALSagaRepository:
    public: true
    arguments:
      - '@doctrine.dbal.default_connection'
      - 'sagas'

  Broadway\EventStore\Dbal\DBALEventStore:
    public: true
    arguments:
      - '@doctrine.dbal.default_connection'
      - '@broadway.serializer.payload'
      - '@broadway.serializer.metadata'
      - 'events'
      - false
      - '@broadway.uuid.converter'

  ### Saga

  Backend\Api\User\Application\Saga\UserSaga:
    arguments:
      - '@tactician.commandbus.command.create.user'
      - '@Backend\Api\User\Domain\Factory\CommandFactory'
    public: true
    tags:
      - { name: broadway.saga, type: api.user }

