services:
  _defaults:
    autowire: true
    autoconfigure: false
    public: false

  MicroModule\Task\Application\Processor\JobCommandBusProcessor:
    arguments:
      - '@Enqueue\JobQueue\JobRunner'
      - '@tactician.commandbus.command.create.user'
      - '@Backend\Api\User\Domain\Factory\CommandFactory'
      - '@broadway.event_dispatcher'
    calls:
      - [setLogger, ['@logger']]
    tags:
      - { name: 'enqueue.command_subscriber', client: 'task' }
